# Generated by Django 2.0.5 on 2018-05-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180508_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
